
export const  showLandingPage = (req,res) => {
    res.render("landingHome")
}

export const checkOutPage = (req, res) => {
    const { price, title } = req.query;
    const decodedTitle = decodeURIComponent(title);
    let info = ""
    let imagenPlan = ""
    if(decodedTitle === "Clases de Entrenamiento"){
        imagenPlan = "/img/clasesDeEntrenamiento.webp"
        info = "¡Bienvenido al emocionante mundo del fitness en nuestro gimnasio! Estamos encantados de ofrecerte nuestro excepcional plan de clases de entrenamiento, diseñado para llevarte más allá de tus límites y ayudarte a alcanzar tus metas de forma efectiva y divertida. Nuestro plan de clases de entrenamiento te brinda acceso a una amplia variedad de sesiones diseñadas por expertos en fitness. Desde intensos entrenamientos cardiovasculares que pondrán a prueba tu resistencia hasta sesiones de fuerza que te ayudarán a tonificar y fortalecer cada músculo de tu cuerpo, nuestro equipo de entrenadores altamente capacitados está comprometido en guiarte en cada paso del camino. Ya sea que estés buscando perder peso, aumentar tu energía, mejorar tu resistencia o simplemente mantenerte activo y saludable, nuestras clases de entrenamiento están diseñadas para adaptarse a tus objetivos individuales. Además, te brindamos un ambiente motivador y lleno de camaradería, donde podrás entrenar junto a personas que comparten tu entusiasmo por un estilo de vida activo. No importa tu nivel de condición física actual, nuestro plan de clases de entrenamiento es apto para principiantes y entusiastas del fitness por igual. Así que, ¿estás listo para desafiarte a ti mismo, superar tus límites y descubrir tu mejor versión? Únete a nosotros en esta emocionante aventura de transformación física y mental. ¡Tu viaje hacia una vida más saludable y enérgica comienza aquí en nuestro gimnasio!"
    }else if(decodedTitle === "Entrenamiento Personalizado"){
        imagenPlan = "/img/clasesPersonalizadas.jpg"
        info = "¡Prepárate para transformar por completo tu cuerpo y tu vida con nuestro exclusivo y revolucionario Plan de Entrenamiento Personalizado! Sabemos que cada persona es única, con metas y desafíos distintos, por lo que hemos creado un programa completamente adaptado a ti. Imagina alcanzar tus objetivos de fitness de manera rápida y sostenible, con un equipo de entrenadores altamente calificados a tu disposición en cada paso del camino. Nuestro enfoque no es solo un plan de ejercicios, sino una experiencia completa de transformación. Desde el momento en que te unes a nosotros, recibirás una evaluación exhaustiva de tu estado físico, estilo de vida y objetivos personales. Con esta información en mano, nuestros expertos diseñarán un plan de entrenamiento a medida que abarque desde ejercicios de fuerza y cardio hasta sesiones de flexibilidad y recuperación. Pero eso no es todo. Te brindaremos orientación nutricional precisa y personalizada, asegurando que tu alimentación sea un apoyo vital en tu viaje hacia el éxito. Además, te mantendremos motivado y enfocado a través de sesiones de seguimiento y ajustes continuos en tu plan, para asegurarnos de que estás en el camino correcto hacia tus metas. Imagina cómo te sentirás cuando comiences a ver y sentir los resultados reales: más energía, más confianza y una versión más fuerte y saludable de ti mismo. Este plan no se trata solo de perder peso o ganar músculo, se trata de empoderarte y transformar tu vida por completo. No te conformes con menos de lo que mereces. Invita al cambio y al éxito con nuestro Plan de Entrenamiento Personalizado. Estamos comprometidos a ayudarte a alcanzar tus sueños y a ser el mejor tú posible. ¡El momento de invertir en ti mismo es ahora! ¡Únete a nuestra comunidad y comienza tu emocionante viaje hacia una vida más saludable, vibrante y en forma hoy mismo!"
    }else{
        imagenPlan = "/img/areaDeCardio.jpg"
        info = "¡Maximiza tu potencial cardiovascular y desata la energía interior con nuestro increíble Plan de Área de Cardio! En nuestro gimnasio, sabemos que el cardio es esencial para alcanzar un estado físico óptimo y mantener un corazón fuerte y saludable. Es por eso que hemos creado un plan diseñado específicamente para llevar tus entrenamientos cardiovasculares al siguiente nivel. Imagina cada latido de tu corazón impulsándote hacia nuevas alturas de resistencia y vitalidad. Con nuestro Plan de Área de Cardio, tendrás acceso ilimitado a una amplia gama de equipos de cardio de última generación. Desde cintas de correr y bicicletas estáticas hasta máquinas elípticas y escaladoras, tendrás todas las herramientas que necesitas para variar tus entrenamientos y mantenerlos frescos y emocionantes. Nuestro equipo de entrenadores altamente calificados estará a tu disposición para brindarte orientación experta y personalizada. Te ayudarán a establecer objetivos claros, a crear planes de entrenamiento efectivos y a monitorear tu progreso a medida que avanzas en tu viaje hacia la salud cardiovascular. Además, te proporcionaremos consejos y técnicas avanzadas para optimizar tus entrenamientos y alcanzar tus metas con mayor rapidez. No importa si eres un principiante que busca mejorar su resistencia o un atleta experimentado que busca perfeccionar su rendimiento, nuestro Plan de Área de Cardio es perfecto para ti. Descubre cómo tu cuerpo y tu mente se fortalecen a medida que te sumerges en sesiones de cardio que desafían tus límites y te llenan de energía positiva. Prepárate para disfrutar de los beneficios de un corazón más saludable, una mayor resistencia y una mejor condición física en general. Conviértete en la mejor versión de ti mismo mientras te sumerges en un mundo de posibilidades en nuestro gimnasio. ¡No esperes más para unirte a nosotros y comenzar tu emocionante viaje hacia un estilo de vida activo y lleno de vitalidad con nuestro extraordinario Plan de Área de Cardio!"
    }
    res.render('checkout', { price, title: decodedTitle, info, imagenPlan });
};